# Scanner System Configuration
# Main configuration file for 4DOF scanner system

# System Configuration
system:
  name: "4DOF Scanner V2.0"
  debug_mode: false
  simulation_mode: false  # Set to true for testing without hardware
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  
# Hardware Platform
platform:
  type: "raspberry_pi_5"
  gpio_library: "gpiozero"  # gpiozero with RPi.GPIO factory - no pigpiod required
  camera_interface: "libcamera"  # Pi5 camera system

# Motion Control Configuration
motion:
  controller:
    type: "fluidnc"
    connection: "usb"
    port: "/dev/ttyUSB0"  # Adjust as needed - may be /dev/ttyACM0
    baudrate: 115200      # From FluidNC default
    timeout: 10.0
    
  # I2S Stepper Engine Configuration (From FluidNC)
  hardware:
    engine: "I2S_STREAM"  # From FluidNC stepping.engine
    i2s_pins:
      bck_pin: 22         # From FluidNC i2so.bck_pin: gpio.22
      data_pin: 21        # From FluidNC i2so.data_pin: gpio.21  
      ws_pin: 17          # From FluidNC i2so.ws_pin: gpio.17
    pulse_timing:
      pulse_us: 4         # From FluidNC stepping.pulse_us
      min_pulse_us: 2     # From FluidNC i2so.min_pulse_us
    
  # Axis Configuration and Limits (Matching FluidNC hardware)
  axes:
    x_axis:
      type: "linear"
      units: "mm"
      min_limit: 0.0
      max_limit: 200.0              # From FluidNC max_travel_mm
      home_position: 0.0
      max_feedrate: 1000            # From FluidNC max_rate_mm_per_min
      steps_per_mm: 800             # From FluidNC configuration
      has_limits: true              # Has limit switches (gpio.16)
      homing_required: true         # Part of homing cycle 2
      
    y_axis:
      type: "linear" 
      units: "mm"
      min_limit: 0.0
      max_limit: 200.0              # From FluidNC max_travel_mm
      home_position: 200.0          # From FluidNC mpos_mm (homes to max)
      max_feedrate: 1000            # From FluidNC max_rate_mm_per_min
      steps_per_mm: 800             # From FluidNC configuration
      has_limits: true              # Has both neg (gpio.13) and pos (gpio.4) limits
      homing_required: true         # Part of homing cycle 1
      
    z_axis:
      type: "rotational"
      units: "degrees"
      min_limit: -180.0             # Practical limit for continuous rotation
      max_limit: 180.0              # 360mm travel from FluidNC
      home_position: 0.0
      max_feedrate: 800             # From FluidNC max_rate_mm_per_min (converted to degrees/min)
      steps_per_mm: 1422            # From FluidNC (actually steps per degree)
      has_limits: false             # No limit switches in FluidNC config
      homing_required: false        # Not part of homing cycles
      continuous: true              # Continuous rotation capability
      
    c_axis:
      type: "rotational"
      units: "degrees"
      min_limit: -90.0              # Servo range (180mm travel = 180 degrees)
      max_limit: 90.0               # From FluidNC max_travel_mm converted
      home_position: 90.0           # Servo home position (center of range)
      default_position: 0.0         # Default position when not homed
      max_feedrate: 5000            # From FluidNC max_rate_mm_per_min (very fast servo)
      steps_per_mm: 300             # From FluidNC configuration
      has_limits: false             # Soft limits only in FluidNC
      homing_required: false        # Homing cycle 0 (not used)
      servo_controlled: true        # RC servo on gpio.26
      continuous: false             # Limited range servo
  
  # Feedrate Configuration - Per Axis and Operating Mode
  feedrates:
    # MANUAL/JOG MODE - Fast and responsive for web interface jog commands
    manual_mode:
      x_axis: 950.0              # mm/min - 95% of max (1000) - near maximum speed
      y_axis: 950.0              # mm/min - 95% of max (1000) - near maximum speed  
      z_axis: 750.0              # deg/min - 94% of max (800) - near maximum rotation
      c_axis: 4800.0             # deg/min - 96% of max (5000) - near maximum servo speed
      description: "Near-maximum feedrates for very responsive web interface"
      
    # SCANNING MODE - Fast but precise for automated scanning operations  
    scanning_mode:
      x_axis: 850.0              # mm/min - 85% of max - fast precision positioning
      y_axis: 850.0              # mm/min - 85% of max - fast precision positioning
      z_axis: 650.0              # deg/min - 81% of max - fast smooth rotation
      c_axis: 4000.0             # deg/min - 80% of max - fast precise camera positioning
      description: "High-speed feedrates for faster automated scanning operations"
      
    # CONFIGURATION OPTIONS
    options:
      allow_override: true       # Allow runtime feedrate override
      validate_limits: true     # Validate against max_feedrate limits
      apply_acceleration: true   # Use acceleration profiles
      
  # Safety Configuration (Matching FluidNC requirements)
  safety:
    enable_limits: true
    must_home: true               # From FluidNC start.must_home: true
    check_limits: true            # From FluidNC start.check_limits: true
    safe_height_z: 0.0            # Safe Z rotation position
    safe_tilt_c: 0.0              # Safe camera tilt position (servo default)
    collision_detection: true
    emergency_stop_enabled: true
    
  # Homing Configuration (From FluidNC homing cycles)
  homing:
    enable: true
    runs: 2                       # From FluidNC axes.homing_runs: 2
    seek_rate: 500                # From FluidNC homing.seek_mm_per_min
    feed_rate: 100                # From FluidNC homing.feed_mm_per_min
    pulloff_distance: 5.0         # From FluidNC pulloff_mm
    sequence:
      - axis: "y"                 # Homing cycle 1
        direction: "positive"     # mpos_mm: 200 (homes to max)
      - axis: "x"                 # Homing cycle 2  
        direction: "negative"     # positive_direction: false
    
# Camera Configuration
cameras:
  system_type: "dual_camera"
  
  camera_1:
    port: 0
    name: "Primary Camera"
    resolution:
      capture: [3280, 2464]  # High-res for photos
      preview: [1280, 720]   # Lower-res for streaming
    format: "jpeg"
    quality: 95
    
  camera_2:
    port: 1  
    name: "Secondary Camera"
    resolution:
      capture: [3280, 2464]  # High-res for photos
      preview: [1280, 720]   # Lower-res for streaming
    format: "jpeg"
    quality: 95
    
  synchronization:
    enable: true
    tolerance_ms: 10  # Acceptable sync difference
    
  streaming:
    enable: true
    fps: 30
    quality: 70
    
# LED Flash Configuration  
# gpiozero PWM Setup: Uses gpiozero.LED with frequency property at 300Hz
# LED.value for duty cycle control, LED.frequency for PWM frequency
lighting:
  controller_type: "gpiozero"       # Use gpiozero LED controller
  use_pigpio_factory: false         # Use RPi.GPIO factory (no pigpiod required)
  pwm_frequency: 300                # Hz - PWM frequency via LED.frequency property
  
  zones:
    inner:
      gpio_pins: [12]      # Inner flash ring - PWM-capable pin (avoiding I2S pins 17,21,22)
      led_type: "cool_white"
      max_current_ma: 800
      position: [0.0, 0.0, 80.0]    # X, Y, Z position in mm
      direction: [0.0, 0.0, -1.0]   # Pointing down
      beam_angle: 30.0
      max_brightness: 0.9           # 90% safety limit
      
    outer:
      gpio_pins: [13]      # Outer flash ring - PWM-capable pin (avoiding FluidNC limit pins)
      led_type: "cool_white" 
      max_current_ma: 1000
      position: [0.0, 0.0, 80.0]    # X, Y, Z position in mm
      direction: [0.0, 0.0, -1.0]   # Pointing down
      beam_angle: 60.0
      max_brightness: 0.9           # 90% safety limit
  
  # Safety Configuration
  safety:
    max_duty_cycle: 0.89          # 89% maximum to prevent hardware damage
    thermal_protection: true
    flash_timeout_seconds: 5.0
      
  # Hardware Notes:
  # - Avoid GPIO 17,21,22 (I2S stepper control)
  # - Avoid GPIO 16 (X-axis limit), GPIO 13,4 (Y-axis limits) 
  # - Avoid GPIO 26 (C-axis servo)
  # - Use GPIO 12,13 or other PWM-capable pins
  
  flash_profiles:
    standard:
      pre_flash_ms: 50
      main_flash_ms: 100
      intensity_percent: 70.0
      
    macro:
      pre_flash_ms: 30
      main_flash_ms: 150
      intensity_percent: 85.0
      
    low_power:
      pre_flash_ms: 20
      main_flash_ms: 80
      intensity_percent: 50.0
  
  safety:
    max_continuous_ms: 200  # Never flash longer than 200ms
    cooldown_ms: 1000       # Minimum time between flashes
    auto_shutoff: true      # Auto turn off if system error
    
# Web Interface Configuration
web_interface:
  host: "0.0.0.0"  # Listen on all interfaces
  port: 5000
  debug: false
  
  features:
    streaming: true
    manual_control: true
    scan_monitoring: true
    file_browser: true
    
  security:
    authentication: false  # Set to true for password protection
    cors_enabled: true
    
# Data Storage Configuration  
storage:
  base_path: "/home/user/scanner_data"
  
  organization:
    use_date_folders: true
    use_session_folders: true
    
  formats:
    photos: "jpeg"
    metadata: "json"
    logs: "txt"
    
  backup_enabled: false
    
# Communication Configuration
communication:
  data_transfer:
    method: "network"  # network, usb, or disabled
    destination_ip: "192.168.1.100"  # PC IP address
    port: 8080
    auto_transfer: false
    
# Scan Configuration Defaults
scanning:
  default_stabilization_delay: 1.0  # Seconds to wait after movement (general)
  scan_stabilization_delay: 2.0     # Extended delay for scanning precision
  default_capture_delay: 0.5        # Additional delay before capture
  
  path_planning:
    default_overlap_percent: 20
    default_safety_margin: 5.0  # mm
    
  session_management:
    auto_save_metadata: true
    auto_generate_thumbnails: true
    max_session_duration_hours: 4